{% set version = "0.2.0.post0" %}

package:
  name: mo_pack
  version: {{ version }}

source:
  url: https://github.com/SciTools/mo_pack/archive/v{{ version }}.tar.gz
  sha256: 9c4b355d1b21b262fa82ca7ab508d8fb236b83c19660bcc503f01506f5699f89

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - libmo_unpack
  run:
    - python
    - libmo_unpack
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mo_pack

about:
    home: https://github.com/SciTools/mo_pack
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'Python wrapper to libmo_unpack'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - lbdreyer
    - bjlittle
