{% set version = "0.2.0" %}

package:
  name: mo_pack
  version: {{ version }}

source:
  url: https://github.com/SciTools/mo_pack/archive/v{{ version }}.tar.gz
  sha256: 4aa70e1f846b666670843bc2514435dedf7393203e88abaf74d48f8f2717a726

build:
  number: 1008
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - libmo_unpack
  run:
    - python
    - libmo_unpack
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mo_pack

about:
    home: https://github.com/SciTools/mo_pack
    license: LGPL-3.0
    license_file: COPYING.LESSER
    summary: 'Python wrapper to libmo_unpack'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
